# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_pyqt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.PushButton_5 = PushButton(self.groupBox)
        self.PushButton_5.setGeometry(QtCore.QRect(40, 100, 111, 41))
        self.PushButton_5.setObjectName("PushButton_5")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 331, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(100, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 260, 125))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ComboBox = ComboBox(self.layoutWidget)
        self.ComboBox.setObjectName("ComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LineEdit = LineEdit(self.layoutWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PushButton = PushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton.sizePolicy().hasHeightForWidth())
        self.PushButton.setSizePolicy(sizePolicy)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_2.addWidget(self.PushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.PushButton_2 = PushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_2.sizePolicy().hasHeightForWidth())
        self.PushButton_2.setSizePolicy(sizePolicy)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.LineEdit_2 = LineEdit(self.tab)
        self.LineEdit_2.setGeometry(QtCore.QRect(410, 150, 351, 55))
        self.LineEdit_2.setMinimumSize(QtCore.QSize(0, 55))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.DisplayLabel = DisplayLabel(self.tab)
        self.DisplayLabel.setGeometry(QtCore.QRect(40, 320, 771, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.DisplayLabel.setFont(font)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.PushButton_3 = PushButton(self.tab)
        self.PushButton_3.setGeometry(QtCore.QRect(530, 280, 102, 32))
        self.PushButton_3.setObjectName("PushButton_3")
        self.PushButton_4 = PushButton(self.tab)
        self.PushButton_4.setGeometry(QtCore.QRect(330, 560, 102, 32))
        self.PushButton_4.setObjectName("PushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.TableWidget = TableWidget(self.tab_2)
        self.TableWidget.setGeometry(QtCore.QRect(60, 20, 731, 291))
        self.TableWidget.setStyleSheet("QTableView {\n"
"    background-color: rgb(207, 207, 207);\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"QTableView::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"QTableView::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QTableView::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"QTableView::indicator:checked,\n"
"QTableView::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"QTableView::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"QTableView::indicator:checked:pressed,\n"
"QTableView::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"QTableView::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableView::indicator:checked:disabled,\n"
"QTableView::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}\n"
"\n"
"\n"
"QHeaderView {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"    font: 13px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 7);\n"
"    border-left: none;\n"
"    height: 40px;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal:last {\n"
"    border-right: none;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Down_black.svg);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    margin-right: 6px;\n"
"    image: url(:/qfluentwidgets/images/table_view/Up_black.svg);\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 19);\n"
"}\n"
"\n"
"QTableCornerButton::section:pressed {\n"
"    background-color: rgba(0, 0, 0, 12);\n"
"}")
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.PushButton_6 = PushButton(self.tab_2)
        self.PushButton_6.setGeometry(QtCore.QRect(370, 590, 161, 51))
        self.PushButton_6.setObjectName("PushButton_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 420, 701, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit_3 = LineEdit(self.layoutWidget1)
        self.LineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.horizontalLayout.addWidget(self.LineEdit_3)
        self.LineEdit_4 = LineEdit(self.layoutWidget1)
        self.LineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.horizontalLayout.addWidget(self.LineEdit_4)
        self.LineEdit_5 = LineEdit(self.layoutWidget1)
        self.LineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.horizontalLayout.addWidget(self.LineEdit_5)
        self.LineEdit_6 = LineEdit(self.layoutWidget1)
        self.LineEdit_6.setMinimumSize(QtCore.QSize(0, 50))
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.horizontalLayout.addWidget(self.LineEdit_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 50, 531, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.LineEdit_7 = LineEdit(self.formLayoutWidget)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_7)
        self.LineEdit_8 = LineEdit(self.formLayoutWidget)
        self.LineEdit_8.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_8)
        self.LineEdit_9 = LineEdit(self.formLayoutWidget)
        self.LineEdit_9.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_9)
        self.LineEdit_10 = LineEdit(self.formLayoutWidget)
        self.LineEdit_10.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit_10)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(640, 50, 201, 171))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.LineEdit_11 = LineEdit(self.formLayoutWidget_2)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_11)
        self.LineEdit_12 = LineEdit(self.formLayoutWidget_2)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_12)
        self.LineEdit_13 = LineEdit(self.formLayoutWidget_2)
        self.LineEdit_13.setObjectName("LineEdit_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_13)
        self.PushButton_7 = PushButton(self.tab_3)
        self.PushButton_7.setGeometry(QtCore.QRect(90, 260, 191, 71))
        self.PushButton_7.setObjectName("PushButton_7")
        self.PushButton_8 = PushButton(self.tab_3)
        self.PushButton_8.setGeometry(QtCore.QRect(390, 300, 102, 32))
        self.PushButton_8.setObjectName("PushButton_8")
        self.PushButton_9 = PushButton(self.tab_3)
        self.PushButton_9.setGeometry(QtCore.QRect(390, 260, 102, 32))
        self.PushButton_9.setObjectName("PushButton_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 390, 421, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(40, 30, 355, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RadioButton = RadioButton(self.widget)
        self.RadioButton.setObjectName("RadioButton")
        self.horizontalLayout_3.addWidget(self.RadioButton)
        self.RadioButton_2 = RadioButton(self.widget)
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.horizontalLayout_3.addWidget(self.RadioButton_2)
        self.RadioButton_3 = RadioButton(self.widget)
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.horizontalLayout_3.addWidget(self.RadioButton_3)
        self.DisplayLabel_2 = DisplayLabel(self.groupBox_4)
        self.DisplayLabel_2.setGeometry(QtCore.QRect(40, 70, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(63)
        self.DisplayLabel_2.setFont(font)
        self.DisplayLabel_2.setObjectName("DisplayLabel_2")
        self.RadioButton_4 = RadioButton(self.tab_3)
        self.RadioButton_4.setGeometry(QtCore.QRect(560, 430, 113, 24))
        self.RadioButton_4.setObjectName("RadioButton_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 70, 701, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PushButton_10 = PushButton(self.tab_4)
        self.PushButton_10.setGeometry(QtCore.QRect(350, 330, 102, 32))
        self.PushButton_10.setObjectName("PushButton_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.ToggleButton = ToggleButton(self.tab_5)
        self.ToggleButton.setGeometry(QtCore.QRect(60, 90, 112, 32))
        self.ToggleButton.setObjectName("ToggleButton")
        self.SwitchButton = SwitchButton(self.tab_5)
        self.SwitchButton.setGeometry(QtCore.QRect(60, 180, 91, 37))
        self.SwitchButton.setObjectName("SwitchButton")
        self.Slider = Slider(self.tab_5)
        self.Slider.setGeometry(QtCore.QRect(490, 120, 311, 271))
        self.Slider.setObjectName("Slider")
        self.TransparentDropDownPushButton = TransparentDropDownPushButton(self.tab_5)
        self.TransparentDropDownPushButton.setGeometry(QtCore.QRect(50, 280, 266, 30))
        self.TransparentDropDownPushButton.setObjectName("TransparentDropDownPushButton")
        self.TransparentTogglePushButton = TransparentTogglePushButton(self.tab_5)
        self.TransparentTogglePushButton.setGeometry(QtCore.QRect(130, 400, 219, 30))
        self.TransparentTogglePushButton.setObjectName("TransparentTogglePushButton")
        self.DropDownToolButton = DropDownToolButton(self.tab_5)
        self.DropDownToolButton.setGeometry(QtCore.QRect(530, 440, 60, 32))
        self.DropDownToolButton.setObjectName("DropDownToolButton")
        self.TransparentDropDownPushButton_2 = TransparentDropDownPushButton(self.tab_5)
        self.TransparentDropDownPushButton_2.setGeometry(QtCore.QRect(160, 480, 266, 30))
        self.TransparentDropDownPushButton_2.setObjectName("TransparentDropDownPushButton_2")
        self.CheckBox = CheckBox(self.tab_5)
        self.CheckBox.setGeometry(QtCore.QRect(320, 180, 92, 22))
        self.CheckBox.setObjectName("CheckBox")
        self.EditableComboBox = EditableComboBox(self.tab_5)
        self.EditableComboBox.setGeometry(QtCore.QRect(110, 550, 157, 33))
        self.EditableComboBox.setObjectName("EditableComboBox")
        self.PushButton_11 = PushButton(self.tab_5)
        self.PushButton_11.setGeometry(QtCore.QRect(340, 80, 241, 51))
        self.PushButton_11.setObjectName("PushButton_11")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PushButton_5.setText(_translate("MainWindow", "加载数据"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_3.setText(_translate("MainWindow", "表单测试"))
        self.label.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "学号："))
        self.PushButton.setText(_translate("MainWindow", "登陆"))
        self.PushButton_2.setText(_translate("MainWindow", "注册"))
        self.DisplayLabel.setText(_translate("MainWindow", "Display label"))
        self.PushButton_3.setText(_translate("MainWindow", "Push button"))
        self.PushButton_4.setText(_translate("MainWindow", "打开文件夹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "布局"))
        self.PushButton_6.setText(_translate("MainWindow", "获取当前选中行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "表格控件"))
        self.label_4.setText(_translate("MainWindow", "Normal"))
        self.label_5.setText(_translate("MainWindow", "NoEcho:"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "PasswordEchoOnEdit"))
        self.label_8.setText(_translate("MainWindow", "整数："))
        self.label_9.setText(_translate("MainWindow", "浮点数："))
        self.label_10.setText(_translate("MainWindow", "正则："))
        self.PushButton_7.setText(_translate("MainWindow", "测试按钮"))
        self.PushButton_8.setText(_translate("MainWindow", "关闭"))
        self.PushButton_9.setText(_translate("MainWindow", "启动"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.RadioButton.setText(_translate("MainWindow", "白展堂"))
        self.RadioButton_2.setText(_translate("MainWindow", "祝无双"))
        self.RadioButton_3.setText(_translate("MainWindow", "佟湘玉"))
        self.DisplayLabel_2.setText(_translate("MainWindow", "Display label"))
        self.RadioButton_4.setText(_translate("MainWindow", "Radio button"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "按键与输入"))
        self.PushButton_10.setText(_translate("MainWindow", "绘图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "绘图"))
        self.ToggleButton.setText(_translate("MainWindow", "Toggle button"))
        self.TransparentDropDownPushButton.setText(_translate("MainWindow", "Transparent drop down push button"))
        self.TransparentTogglePushButton.setText(_translate("MainWindow", "Transparent toggle push button"))
        self.TransparentDropDownPushButton_2.setText(_translate("MainWindow", "Transparent drop down push button"))
        self.CheckBox.setText(_translate("MainWindow", "Check box"))
        self.PushButton_11.setText(_translate("MainWindow", "向对话窗口发送信号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "常用控件"))
from qfluentwidgets import CheckBox, ComboBox, DisplayLabel, DropDownToolButton, EditableComboBox, LineEdit, PushButton, RadioButton, Slider, SwitchButton, TableWidget, ToggleButton, TransparentDropDownPushButton, TransparentTogglePushButton
